# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


# Build settings

permalink: /:slug

exclude:
  - _includes/notes_graph.json
  - _data/site-index.json
  - .obsidian
  - obsidian-templates

plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-archives
safe: false 

tag_index_layout: note
tag_index_dir: _tags

cat_index_layout: note
cat_index_dir: /_categories




collections:
  notes:
    output: true
    permalink: /:name/
  media:
    output: true
    permalink: /media/:path
  galleries:
    output: true
    permalink: /gallery/:name/

feed:
  disable_in_development: false
  path: feeds/updates.atom
  tags:
    path: "feeds/tag/"
  collections:
      - notes
      - media
      - galleries



galleries:
  - name: "Pika's Place"
    directory: "pikas-place"
    tags: ["art", "memorial"]
  - name: "Ty Ennis at Nationale"
    directory: "ty-ennis"
    tags: ["art", "nationale"]
  - name: "They Always Have and Still Do"
    directory: "always-have-still-do"
    tags: ["art", "nationale"]