
title: M E M E X D O T C L O U D
email: nimdaghlian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Ním's Memex
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mmmx.cloud" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  nimdaghlian


# Build settings
# incremental: true

permalink: pretty


exclude:
  - _includes/notes_graph.json
  - _data/site-index.json
  - .obsidian
  - obsidian-templates

plugins:
  - jekyll-feed
  - jekyll-last-modified-at
safe: false 

tag_index_layout: tag
tag_index_dir: _tag-pages
permalink: pretty

cat_index_layout: category
cat_index_dir: /_cat-pages

defaults:
  -
    scope:
      path: "_notes"
    values:
      layout: note
  -
    scope:
      path: "_galleries"
    values:
      layout: gallery


collections:
  notes:
    output: true
    permalink: /:name/
  media:
    output: true
    permalink: /media/:path
  galleries:
    output: true
    permalink: /gallery/:name/
  tag-pages:
    output: true
    permalink: /tag/:name/
  cat-pages:
    output: true
    permalink: /category/:name/
feed:
  disable_in_development: true
  path: feed/posts.atom
  collections:
      - notes
      - media
      - galleries



galleries:
  - name: "Pika's Place"
    directory: "pikas-place"
    tags: ["art", "memorial"]
  - name: "Innerbloom"
    directory: "innerbloom"
    tags: ["art", "nationale"]
  - name: "They Always Have and Still Do"
    directory: "always-have-still-do"
    tags: ["art", "nationale"]
  - name: "Notes in General"
    directory: "notes"
    tags: ["mulch", "rando"]
  - name: "EXPOCHGO"
    directory: "EXPOCHGO"
    tags: ["art", "times"]
    parse_date: true
  - name: "Everything in My Wife's Bag Two Days After We Got Married"
    directory: "wife-bag"
    tags: ["life", "things"]
  - name: "Interdependence Day Papercuts"
    directory: "id-papercuts"
    tags:
      - art
      - "interdependence day"
      - traditions
    parse_date: true
  - name: "Coffee We Like"
    directory: "coffee-we-like"
    categories: ["objects"]
    tags: ["coffee", "archives"]
