
title: M E M E X D O T C L O U D
email: nimdaghlian@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Ním's Memex
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  nimdaghlian


# Build settings

permalink: /:slug

exclude:
  - _includes/notes_graph.json
  - _data/site-index.json
  - .obsidian
  - obsidian-templates

plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-archives
safe: false 

tag_index_layout: tag
tag_index_dir: _tags

cat_index_layout: category
cat_index_dir: /_categories




collections:
  notes:
    output: true
    permalink: /:name/
  media:
    output: true
    permalink: /media/:path
  galleries:
    output: true
    permalink: /gallery/:name/
  tags:
    output: true
    permalink: /tag/:name/

feed:
  disable_in_development: false
  path: feeds/updates.atom
  tags:
    path: "feeds/tag/"
  collections:
      - notes
      - media
      - galleries



galleries:
  - name: "Pika's Place"
    directory: "pikas-place"
    tags: ["art", "memorial"]
  - name: "Ty Ennis at Nationale"
    directory: "ty-ennis"
    tags: ["art", "nationale"]
  - name: "They Always Have and Still Do"
    directory: "always-have-still-do"
    tags: ["art", "nationale"]